# Site settings
title: Apprenticeship Service Technical Guidance
email: dan.beavon@education.gov.uk
description: > # this means to ignore newlines until "baseurl:"
  Working Practices

header_links:
  GitHub: https://github.com/SkillsFundingAgency/das-technical-guidance

# Build settings
markdown: kramdown

collections_dir: collections

collections:
  api_standards:
    output: true

  development:
      output: true
  
  architecture:
    output: true

  development_standards:
    output: true

defaults:
-
  scope:
    path: "principles"
  values:
    principle: true

-
  scope:
    path: "standards"
  values:
    standard: true

-
  scope:
    path: "Agile"
  values:
    wow: true
